/**
 * Icon Sprite Builder
 *
 * Generates an SVG sprite from Lucide icons + custom icons.
 * Output: src/icons/sprite.svg
 *
 * Usage: npm run build:icons
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

// Paths
const LUCIDE_DIR = path.join(rootDir, 'node_modules/lucide-static/icons');
const CUSTOM_DIR = path.join(rootDir, 'src/icons/custom');
const OUTPUT_FILE = path.join(rootDir, 'src/icons/sprite.svg');

/**
 * Parse an SVG file and extract its content for sprite symbol
 * @param {string} svgContent - Raw SVG file content
 * @param {string} id - Symbol ID (icon name)
 * @returns {string} Symbol element
 */
function svgToSymbol(svgContent, id) {
  // Extract viewBox
  const viewBoxMatch = svgContent.match(/viewBox="([^"]+)"/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';

  // Extract content (everything between <svg> tags, excluding svg tag itself)
  const contentMatch = svgContent.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  const content = contentMatch ? contentMatch[1].trim() : '';

  return `  <symbol id="${id}" viewBox="${viewBox}">\n    ${content}\n  </symbol>`;
}

/**
 * Read and process all icons from a directory
 * @param {string} dir - Directory path
 * @param {string} prefix - ID prefix (e.g., 'custom-')
 * @returns {Promise<Array<{id: string, symbol: string}>>}
 */
async function readIcons(dir, prefix = '') {
  try {
    await fs.access(dir);
  } catch {
    // Directory doesn't exist
    return [];
  }

  const files = await fs.readdir(dir);
  const svgFiles = files.filter(f => f.endsWith('.svg'));

  const icons = await Promise.all(
    svgFiles.map(async (file) => {
      const filePath = path.join(dir, file);
      const content = await fs.readFile(filePath, 'utf-8');
      const name = path.basename(file, '.svg');
      const id = `${prefix}${name}`;

      return {
        id,
        symbol: svgToSymbol(content, id)
      };
    })
  );

  return icons.sort((a, b) => a.id.localeCompare(b.id));
}

/**
 * Build the SVG sprite
 */
async function buildSprite() {
  console.log('\n🎨 Building icon sprite...\n');

  // Read Lucide icons
  console.log('  Reading Lucide icons...');
  const lucideIcons = await readIcons(LUCIDE_DIR);
  console.log(`  ✓ ${lucideIcons.length} Lucide icons`);

  // Read custom icons
  console.log('  Reading custom icons...');
  const customIcons = await readIcons(CUSTOM_DIR, 'custom-');
  console.log(`  ✓ ${customIcons.length} custom icons`);

  // Combine all icons
  const allIcons = [...lucideIcons, ...customIcons];
  const totalCount = allIcons.length;

  // Generate sprite SVG
  const sprite = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: none;">
  <!--
    Valiify Short App Icon Sprite

    Contains ${lucideIcons.length} Lucide icons + ${customIcons.length} custom icons = ${totalCount} total

    Usage:
      <svg class="icon" width="24" height="24">
        <use href="/path/to/sprite.svg#icon-name" />
      </svg>

    Custom icons are prefixed with 'custom-'

    Generated by scripts/build-sprite.mjs — do not edit by hand.
    Deliberately carries no build timestamp: this file is checked in, and a
    timestamp made every build dirty the working tree and every diff unreadable.
    Output must stay a pure function of the icon sources.
  -->
${allIcons.map(icon => icon.symbol).join('\n')}
</svg>
`;

  // Ensure output directory exists
  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });

  // Write sprite file
  await fs.writeFile(OUTPUT_FILE, sprite, 'utf-8');

  console.log(`\n  wrote  src/icons/sprite.svg`);
  console.log(`         ${lucideIcons.length}  Lucide icons`);
  console.log(`         ${customIcons.length}  custom icons`);
  console.log(`         ${totalCount}  total\n`);

  // Write icon list for reference
  const iconList = allIcons.map(icon => icon.id).join('\n');
  const listFile = path.join(rootDir, 'src/icons/icon-list.txt');
  await fs.writeFile(listFile, iconList, 'utf-8');
  console.log(`  wrote  src/icons/icon-list.txt (searchable list)\n`);
}

// Run
buildSprite().catch(err => {
  console.error('\n❌ Error building sprite:\n', err);
  process.exit(1);
});
